apiVersion: batch/v1
kind: Job
metadata:
  name: greetings
  labels:
    app: greetings
spec:
  template:
    metadata:
      labels:
        app: greetings
    spec:
      restartPolicy: Never
      containers:
        - name: greetings
          image: im2nguyen/aws-sqs-test:latest
          command: ["./message.sh"]
          env:
            - name: QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: greetings-outputs
                  key: url
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: aws-configuration
                  key: region
          volumeMounts:
            - name: sensitivevars
              mountPath: "/tmp/secrets"
              readOnly: true
      volumes:
        - name: sensitivevars
          secret:
            secretName: workspacesecrets
